### ISSUE TITLE
react native Video with flatList (with multiple video) on Scrolling App not responding and crashed the app

### ISSUE THREAD

**Issue by iasreact1** [TheWidlarzGroup/react-native-video#3058] opened 2023-03-09 15:15 UTC
I am using react-native-video-5.2.1, don't know whether use android exo-Player or mediaPlayer. There are so many videos in the flatlist and when get Scrolled it get stuck the UI and app not responding error, Please help what to do for solving it, but if i use the video plaer to another page for playing the video then it working fine but when playing the video within the Flatlist ANR is coming every time & every Device, Please help ...to overcome it..

**Comment by LucasHimelfarb** [comment] 2023-03-13 18:53
Your UI was blocked because Your UI is likely freezing because the listing is not optimized, either because you are displaying many heavy elements or because there is a design anti-pattern in your code causing multiple renders depending on state variables that are being updated. But without a code sample, it's difficult to know for sure.

**Comment by iasreact1** [comment] 2023-08-08 08:36
@LucasHimelfarb  i have an api call 10 data per page and there is multiple state variable for video play/pause, mute/unmute etc loading opacity, and if i use a log that will print 10 times for the first rendering ...how can i improve the performance?

**Comment by krunalinfynno** [comment] 2023-11-29 10:02
i am getting same issue as well.

**Comment by LucasHimelfarb** [comment] 2023-12-05 14:26
@iasreact1 @krunalinfynno  Im sorry for the late answer. The Flatlist`ve many props to improve perfomance, for example the props "removeClippedSubviews" and "getItemLayout". You can see all props here: https://reactnative.dev/docs/flatlist

If anyone have some issue please share some code to detect common problems

**Comment by trubnikovr** [comment] 2024-04-02 13:27
@LucasHimelfarb 
I'm using a modal with a FlatList inside it as a horizontal slider. I've noticed that if I slide and the video is still playing, then the app crashes.

**Comment by freeboub** [comment] 2024-04-02 13:31
If someone can provide a sample app, it would be very useful to reproduce (and fix) the issue!

**Comment by EuSet** [comment] 2024-05-25 21:23
here is a stack trace if it can be helpful 
![Uploading Screenshot 2024-05-26 at 00.20.42.png…]()

**Comment by EuSet** [comment] 2024-05-25 21:29
here is a stack trace if it can be helpful
![trace](https://github.com/TheWidlarzGroup/react-native-video/assets/79215069/ba5ab067-a244-4327-bb59-791856ef7338)

**Comment by EuSet** [comment] 2024-05-25 21:45
here is a stack trace if it can be helpful. version 6.1.1
![trace](https://github.com/TheWidlarzGroup/react-native-video/assets/79215069/187e210d-5485-4ad4-8c62-ee03c0114175)

**Comment by freeboub** [comment] 2024-06-10 20:34
@KrzysztofMoch can you please have a quick look to this callstack ?

**Comment by freeboub** [comment] 2024-06-10 20:35
regarding to the initial issue, I created a flat list sample here: https://github.com/freeboub/react-native-video-flatlist-sample
It seems to work fine

**Comment by KrzysztofMoch** [comment] 2024-06-10 20:37
> @KrzysztofMoch can you please have a quick look to this callstack ?

Seems like crash is caused by setting some metadata properties (probably image)

**Comment by freeboub** [comment] 2024-06-10 21:50
@EuSet It would need to be tracked in a dedicated ticket

@KrzysztofMoch On this line, asset is nil ?
```js
let metadata = currentItem.asset.commonMetadata + currentItem.externalMetadata
```

**Comment by KrzysztofMoch** [comment] 2024-06-10 21:53
@freeboub no it would crash differently - it will be lower, probably in place when we are setting NowPlayingInfo data eg artwork

**Comment by freeboub** [comment] 2024-06-14 13:09
@EuSet can you please open a new ticket, I close this one.

**Closed as completed by freeboub** 2024-06-14 13:09 UTC
