### ISSUE TITLE
android-exoplayer behavior wrong with resizeMode contain

### ISSUE THREAD

**Issue by bachphuc** [TheWidlarzGroup/react-native-video#1225] opened 2018-09-11 05:55 UTC
### Current behavior
Hi, 
I build video player use react-native-video, it works well before with Android MediaPlayer but it loads slow then I move to Android ExoPlayer and it's faster.

But I see Android ExoPlayer is doing wrong with resizeMode  contain. It doesn't update video content when I change new video source.

### Reproduction steps
First I create Video element with fixed size ratio 16:9 and resizeMode is contain

Second step,  I load a remote video is ratio 1:1 (square)  https://softmedia.cuoibachay.com/videos/video-2282-chu-khi-thong-minh-nhat-the-gio-o-nhat-ban.mp4 . It looks good. square video center of player, correctly.

Then I next to other video (update source) with ratio 16:9 (https://softmedia.cuoibachay.com/videos/video-2293-cach-ngoi-thien-tren-la-sen-khong-lo-o-mien-tay.mp4) then it should be fit player right? but it doesn't. It's till square at center of player like last video.

### Expected behavior
It should behavior correctly with contain mode is contain when update new video to player
### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer 2.8.2

### Video sample
- square video: https://softmedia.cuoibachay.com/videos/video-2282-chu-khi-thong-minh-nhat-the-gio-o-nhat-ban.mp4
16:9 video https://softmedia.cuoibachay.com/videos/video-2293-cach-ngoi-thien-tren-la-sen-khong-lo-o-mien-tay.mp4

**Comment by DISKONEKTeD** [comment] 2018-10-18 03:42
did you ever find a fix for this? I'm guessing the component has to re-render

**Comment by DISKONEKTeD** [comment] 2018-10-18 04:12
the problem is RTCVideo component, it does not re-render, it seems. But when i use the debugger to change it manually, say, its height by a 1 pixel it will suddenly re-render to the proper size

**Comment by guzmanbraso** [comment] 2020-06-18 18:17
Hey @DISKONEKTeD , @bachphuc , better later than never, are you still using this and if so can test the PR #2053 ?

**Closed as completed** 2020-06-30 17:00 UTC
