### ISSUE TITLE
[BUG]: selectedAudioTrack and selectedTextTrack not working in ios.

### ISSUE THREAD

**Issue by rahulnainwalttn** [TheWidlarzGroup/react-native-video#3708] opened 2024-04-24 04:08 UTC
### Version

v6 (Beta)

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

selectedAudioTrack -> I have two audio tracks ( index 0 marked as selected) when I change index 1 it works but after that, it does not work when I change back to index 0.

selectedTextTrack -> On selecting text tracks it is doing nothing.

I am using version [6.0.0-rc.0](https://github.com/react-native-video/react-native-video/compare/v6.0.0-beta.8...v6.0.0-rc.0)

Stream URL - https://bitmovin-a.akamaihd.net/content/sintel/hls/playlist.m3u8

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by freeboub** [comment] 2024-04-29 20:28
closed as duplicate of : https://github.com/react-native-video/react-native-video/issues/3704
I just push a fix for this issue

**Closed as completed by freeboub** 2024-04-29 20:28 UTC
Labels: bug
