### ISSUE TITLE
Black screen trying to play DRM content

### ISSUE THREAD

**Issue by TDUser91** [TheWidlarzGroup/react-native-video#3177] opened 2023-07-19 13:23 UTC
# Bug

## Platform
Which player are you experiencing the problem on:
* Android (Didn't try on other platforms yet)

## Environment info

here are my logs:
```
npx react-native info
info Fetching system and libraries information...
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 4.79 GB / 15.40 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.2.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.0 - ~/Bureau/TD_repo/multiplatform_application_vialis/node_modules/.bin/npm
    Watchman: 20230430.125247.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 31, 33, 34
      Build Tools: 30.0.3, 33.0.0, 34.0.0
      System Images: android-34 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: AI-213.7172.25.2113.9123335
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.8 => 0.71.8 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce

1. create project
2. add code below
...

## Expected behaviour

1.  Play DRM protected content as expected
2.

## Reproducible sample code

I'm having an issue where I cannot play video ***DRM protected content*** (mp4 works fine), I get a ***black screen AND no audio*** but I can retrieve all video data, I can see the progress bar move properly. 

In the rare where it works is that, is when: I put two Video components on the screen (see code sample), I refreshed the app (still got black srcreen and no audio), then remove one of the Video Components and refresh again (here the video and audio play correcly). If I refresh again it stops working again.

My code sample: 

```
import React, { useRef, useState, useEffect } from "react";
import { View, Text, TouchableOpacity, StyleSheet } from "react-native";
import Video, { DRMSettings, DRMType } from "react-native-video";
import VideoPlayer from 'react-native-media-console';

const VideoPlayerView = () => {

    const drmSettings: DRMSettings = {
        type: DRMType.WIDEVINE,
        licenseServer: "https://cwip-shaka-proxy.appspot.com/no_auth",
    };

    return (
        <View>
            <Text style={{ textAlign: 'center' }}>
                Demo Video Player
            </Text>

            {/*  TRY ADDING THIS, refresh, then remove and refresh again
             <View style={{ backgroundColor: "red", height: 300 }}>
                <Text>
                    VideoPlayer Component
                </Text>

                <VideoPlayer
                    style={styles.backgroundVideoPlayer}
                    source={{ uri: "https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd" }}
                    controls={true}
                    paused={false}
                    onLoad={(onLoadData) => { console.log('VIDEO_PLAYER: ' + onLoadData) }}
                    navigator={null}
                    drm={drmSettings}
                />

            </View>  */}

            <View style={{ backgroundColor: "blue", height: 300 }}>
                <Text>
                    Video Component
                </Text>
                <TouchableOpacity>
                    <Video
                        style={styles.backgroundVideo}
                        source={{ uri: "https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd" }}
                        controls={true}
                        paused={false}
                        onLoad={function (onLoadData) {
                            console.log('Video Component onLoadData: ', onLoadData);
                        }}
                        drm={drmSettings}
                        onReadyForDisplay={() => {
                            console.log('onReadyForDisplay')
                        }}
                    />
                </TouchableOpacity>
            </View>
        </View >
    );
}

const styles = StyleSheet.create({
    backgroundVideo: {
        height: 250,
        position: 'relative',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
    },

    backgroundVideoPlayer: {
        height: 250,
        width: 250,
        backgroundColor: 'red',
        position: 'relative',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
    },
});
export default VideoPlayerView;
```

**Comment by freeboub** [comment] 2023-08-03 18:40
No react native video version specified.  I suspect you didn't enable exoplayer on react native video 5.2.1.
In any case you should have a look to the logcat to check if exoplayer rise an error.
I will close the issue, let me know if I should reopen it.

**Comment by bulkinav** [comment] 2023-09-27 13:14
@freeboub please reopen this isuue.

I also faced with same issue (black screen / no audio) - react-native-video@6.0.0-alpha.8

For the test, I'm also trying to play a DRM video using:

```
licenseServer: "https://cwip-shaka-proxy.appspot.com/no_auth",
source={{ uri: "https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd" }}
```

And yes, no any errors in Logcat.

**Comment by bulkinav** [comment] 2023-09-28 16:14
I managed to find out the cause of this problem. When we start the video, we have a black screen, but if we forcibly update the source, the video starts playing.

So, as one of the solutions, we can initialize the player with an empty source value, then after a timeout we send the correct link to the video:

```
const [uri, setUri] = useState('')
...

useEffect(() => {
        setTimeout(() => {
            setUri(route?.params?.uri)
        }, 500)
    }, [route?.params?.uri])
```

Of course, this is a very dirty hack, so would be like to see a fix in the player itself in the future.

**Comment by freeboub** [comment] 2023-12-10 20:56
I just try to reproduce the issue on android emulator with the sample on V6.0.0, I cannot reproduce it.
regarding to the workaround, it looks like it forces some refresh of <Video view.
you need to ensure drm & source props are set only once and doesn't change. I suspect that is the real root cause.
Let's close this issue, let me know if you think I should reopen it.

**Closed as completed by freeboub** 2023-12-10 20:56 UTC

**Comment by dgocoder** [comment] 2023-12-26 19:52
I can confirm this happens with android but not iOS. the fix (which is definitely a hack suggested by @bulkinav works). The issue here is if you use the same player and change the source with drm there is no issue. If you have the player being rendered in a modal for instance and then that component is closed, when you try to spin up the player again in another modal it fails. It seems to have to do with the way the player is getting disposed.

**Comment by freeboub** [comment] 2024-10-05 17:03
If someone have a reproducible sample, I would be happy to investigate. (please provide a github repository).
To be tested with last release, some improvments have been done!
