### ISSUE TITLE
Videos type m3u8 not show in android and ios

### ISSUE THREAD

**Issue by davidgvf** [TheWidlarzGroup/react-native-video#3226] opened 2023-08-30 11:37 UTC
# Bug

## Platform
Which player are you experiencing the problem on:
* iOS
* Android

## Environment info

Library version: 6.0.0-alpha.7
Device: IOS 14 PRO and Pixel 6a

## Steps To Reproduce
Run the app and show the video with m3u8 extension and nothing is seen

1.
2.
...

## Expected behaviour

1.
2.

## Reproducible sample code
<Video
                paused={props.paused}
                style={[styles.backgroundVideo, props.styles]}
                resizeMode={props.resizeMode || 'cover'}
                source={{
                    uri: "https://customer-lcnz5dho53hmoxut.cloudflarestream.com/4fbb85f76a86c26ae79eedcc94b95442/manifest/video.m3u8",
                    type: "m3u8"
                }}
                repeat={props.repeat}
                playInBackground={true}
                onBuffer={e => e.isBuffering !== isBuffering && setIsBuffering(e.isBuffering)}
                onLoad={() => setIsLoading(false)}
            />

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.
https://customer-lcnz5dho53hmoxut.cloudflarestream.com/4fbb85f76a86c26ae79eedcc94b95442/manifest/video.m3u8

**Comment by freeboub** [comment] 2023-09-03 13:16
video looks good, did you try in basic sample provided in the package ? (available on master branch)

**Comment by iosdevchakshu** [comment] 2023-09-03 17:41
Hi 
I have same problem with [https://d1q7pblbhnm6jb.cloudfront.net/video/video541693132448984.m3u8](https://d1q7pblbhnm6jb.cloudfront.net/video/video541693132448984.m3u8) file working on android. But only playing audio Not video.
Thanks in advance

**Comment by meetp-zluck** [comment] 2023-09-05 06:13
Hi, We are facing the same for iOS > 16. m3u8 video does not appear. Does anybody know the solution?

**Comment by freeboub** [comment] 2023-09-05 06:46
Test on emulator iphone 14, ios 16.2:
https://customer-lcnz5dho53hmoxut.cloudflarestream.com/4fbb85f76a86c26ae79eedcc94b95442/manifest/video.m3u8 -> work fine on my side. Notice that it plays on safari, but not in VLC. I suspect an encoding issue

 https://d1q7pblbhnm6jb.cloudfront.net/video/video541693132448984.m3u8 -> doesn't work. works on vlc and safari. I suspect something strange with video encoding. 

Can you confirm my findings please ?

**Comment by nicolaosm** [comment] 2023-09-05 17:48
https://d1q7pblbhnm6jb.cloudfront.net/video/video541693132448984.m3u8
https://customer-lcnz5dho53hmoxut.cloudflarestream.com/4fbb85f76a86c26ae79eedcc94b95442/manifest/video.m3u8

Test on emulator Android 11, Pixel 4:
Both videos worked fine.

**Comment by davidgvf** [comment] 2023-09-06 16:33
In android it fine, but in ios never reproduce vídeo m3u8 , i check in simulator and in real device compile app and not work vídeo @nicolaosm

**Comment by davidgvf** [comment] 2023-09-14 07:24
Please help!

**Comment by davidgvf** [comment] 2023-09-27 14:42
Does anyone know something?

**Comment by davidgvf** [comment] 2023-09-27 15:01
@nicolaosm i obtain this error:
{"error": {"code": -1005, "domain": "NSURLErrorDomain", "localizedDescription": "The network connection was lost.", "localizedFailureReason": "", "localizedRecoverySuggestion": ""}, "target": 159}


my video:
https://customer-lcnz5dho53hmoxut.cloudflarestream.com/6a323eb344ca4edf148db60db4c094e9/manifest/video.m3u8

**Comment by wolfxpertlab** [comment] 2023-10-03 05:40
same issue how can I play in android .m3u8 video

please also tell me how can I upload .m3u8 in react native

**Comment by billyjacoby** [comment] 2023-10-13 23:14
I'm seeing this error,  but only with certain videos on iOS 17 as well.

The specific error I'm seeing is:
```json
{
"error":  {
"code": -12746, 
"domain": "CoreMediaErrorDomain", 
"localizedDescription": "The operation couldn’t be completed. (CoreMediaErrorDomain error -12746.)", "localizedFailureReason": "", 
"localizedRecoverySuggestion": ""
}, 
"target": 7073
}
```

Happy to provide any details necessary here.

**Comment by ZakirBangash** [comment] 2023-10-21 22:09
I am experiencing an issue on Android Pixel 4A, it plays the video but takes 3, or 5 minutes, while it is fine on all other devices.

**Comment by john-dududu** [comment] 2024-01-18 08:06
Is there any progress？

**Comment by pozorada** [comment] 2024-02-14 02:55
I've got the same problem on iOS (17.0) (emulator)
 ```
 {
    "error": {
      "localizedDescription": "The operation couldn’t be completed. (NSURLErrorDomain error -1013.)",
      "domain": "NSURLErrorDomain",
      "localizedFailureReason": "",
      "localizedRecoverySuggestion": "",
      "code": -1013
    },
    "target": 1153
  }
```

any ideas what's going on here?

**Comment by freeboub** [comment] 2024-03-27 21:59
I will close this issue as it is a mess now.. 
Please be sure you follow all debugging clues from this page:
https://react-native-video.github.io/react-native-video/other/debug
You can re open tickets, but you need to ensure the issue is linked to react-native-video, not its dependancies !

**Closed as completed by freeboub** 2024-03-27 21:59 UTC

**Comment by Michota** [comment] 2024-05-09 19:33
I would like to reopen this problem. 
There is no chance to see a video (but there is a sound playing) if its in `m3u8` file.

**Comment by Michota** [comment] 2024-05-09 19:33
> I will close this issue as it is a mess now.. Please be sure you follow all debugging clues from this page: https://react-native-video.github.io/react-native-video/other/debug You can re open tickets, but you need to ensure the issue is linked to react-native-video, not its dependancies !

404

**Comment by freeboub** [comment] 2024-05-10 09:24
Yep, url has change: https://thewidlarzgroup.github.io/react-native-video/other/debug

**Comment by mnjoyanx** [comment] 2025-04-15 11:02
{
    "error": {
        "localizedRecoverySuggestion": "",
        "code": -11848,
        "localizedFailureReason": "The media cannot be used on this device.",
        "localizedDescription": "Cannot Open",
        "domain": "AVFoundationErrorDomain"
    },
    "target": 3642
}

Trying to set text track
