### ISSUE TITLE
[BUG]: Version upgrade, from 5.2.1 -> 6.4.5, android client, problems encountered during build. react- native version: 0.65.1

### ISSUE THREAD

**Issue by newyoung21** [TheWidlarzGroup/react-native-video#4138] opened 2024-09-03 06:34 UTC
### Version

6.4.5

### What platforms are you having the problem on?

Android

### System Version

android

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

Configure project :react-native-video
Kotlin version is correct: 1.8.0
useExoplayerIMA: false
useExoplayerSmoothStreaming: true
useExoplayerDash: true
useExoplayerHls: true
useExoplayerRtsp: false
buildFromSource: false

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.google.guava:guava:32.1.3-android.
     Required by:
         project :app
      > The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug'. However we cannot choose between the following variants of com.google.guava:guava:32.1.3-android:
          - androidApiElements
          - jreApiElements
        All of them match the consumer attributes:
          - Variant 'androidApiElements' capabilities com.google.collections:google-collections:32.1.3-android and com.google.guava:guava:32.1.3-android declares an API of a component:
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Provides a library but the consumer didn't ask for it
                  - Provides its dependencies declared externally but the consumer didn't ask for it
                  - Provides attribute 'org.gradle.jvm.environment' with value 'android' but the consumer didn't ask for it
                  - Provides compatibility with Java 8 but the consumer didn't ask for it
                  - Provides its elements packaged as a jar but the consumer didn't ask for it
                  - Provides release status but the consumer didn't ask for it
          - Variant 'jreApiElements' capabilities com.google.collections:google-collections:32.1.3-android and com.google.guava:guava:32.1.3-android declares an API of a component:
              - Unmatched attributes:
                  - Doesn't say anything about com.android.build.api.attributes.BuildTypeAttr (required 'debug')
                  - Provides a library but the consumer didn't ask for it
                  - Provides its dependencies declared externally but the consumer didn't ask for it
                  - Provides attribute 'org.gradle.jvm.environment' with value 'standard-jvm' but the consumer didn't ask for it
                  - Provides compatibility with Java 8 but the consumer didn't ask for it
                  - Provides its elements packaged as a jar but the consumer didn't ask for it
                  - Provides release status but the consumer didn't ask for it

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings

### Reproduction Link

repository link

### Reproduction

implement   ./gradlew assembleRelease

**Comment by freeboub** [comment] 2024-09-03 06:41
It is a dependancy resolution issue. I think prior to this error you should have the warning which are indicating which url is tried to be used to download com.google.guava:guava:32.1.3-android. Can you please check that ?
I hope the dep hasn't been removed from google repo ... 
0.65.1 is very very old also :/ If I were you I would start by updating react native ...

possible root cause can be the repositories definition:

```
    repositories {
        google()
        mavenCentral()
    }
```

**Comment by freeboub** [comment] 2024-09-03 06:42
Note on first page of the doc:

`Version 6.x requires react-native >= 0.68.2`

**Comment by newyoung21** [comment] 2024-09-03 06:50
> Note on first page of the doc:
> 
> `Version 6.x requires react-native >= 0.68.2`

Thanks for your reply. These problems occur in version 5.2.1
{"error":{"extra":-19,"what":1}}
{"error":{"extra":0,"what":-38}}
If you don't upgrade the version, how can you solve it?

**Comment by freeboub** [comment] 2024-09-03 06:58
no idea of your issue with more information ... but clearly you work on an outdated project :/

**Comment by seyedmostafahasani** [comment] 2024-09-03 09:08
@freeboub 
We don't support v5.2.1, so we can close this issue.

**Closed as completed** 2024-09-05 19:41 UTC
Labels: bug, Platform: Android, needs-info, Repro Provided
