### ISSUE TITLE
Please add picture-in-picture mode for android.

### ISSUE THREAD

**Issue by amm4ryous4f** [TheWidlarzGroup/react-native-video#3335] opened 2023-11-07 07:07 UTC
# Feature Request

Please add picture-in-picture mode for android also.

## Why it is needed

To play the video even app is minimized

**Comment by freeboub** [comment] 2023-11-07 07:40
Duplicate of https://github.com/react-native-video/react-native-video/issues/2621

**Closed as completed** 2023-11-07 07:40 UTC
