### ISSUE TITLE
Media Codec video render error

### ISSUE THREAD

**Issue by rohitsingh2410** [TheWidlarzGroup/react-native-video#2834] opened 2022-08-31 15:02 UTC
# Bug
    "react-native-video": "^5.2.0",
   **See screenshot for detailed error log**
Video play for first time fine but it start throwing this error when played 3rd time in a row.

## Platform

Which player are you experiencing the problem on:

* Android

## Environment info

React native info output:

```bash
System:
    OS: macOS 11.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 96.88 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.1 - /usr/local/bin/node
    npm: 7.3.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 23, 26, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-29 | Android TV Intel x86 Atom, android-30 | Android TV Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: x.x.x

## Steps To Reproduce

1. Download 2,3 video using react native fs, save to file system.
2. when played on one after another it gives **Unable to instantiate decoder OMX.MTK.VIDEO.DECODER.AVC** error.
3. 
...

## Video sample
Any video downloaded in file system

![image](https://user-images.githubusercontent.com/17305828/187711684-2c0d9462-e84e-4c07-961a-82ee22db0a4a.png)

**Comment by freeboub** [comment] 2022-09-03 11:49
This issue is typically due to issue in codec release from player.
Are you able to reproduce the issue with sample ? maybe with a patched version of basic sample in the repo ?!

**Comment by evoactivity** [comment] 2022-09-28 22:51
Hi @rohitsingh2410
If you could answer some questions you can help move this issue along.

Have you tried 5.2.1 or any of the v6 alphas?
Are you looping the video?
Can you share some sample code?

If you have fixed it yourself in some way please let us know or close the issue. Thank you 🙂

**Comment by EvgenMarchuk-art** [comment] 2022-11-11 00:17
Good night, I have the same problem on android.
<img width="1002" alt="Screenshot 2022-11-11 at 01 09 07" src="https://user-images.githubusercontent.com/61016903/201232036-d72f0290-d6d8-44c3-aff5-87e063599927.png">
the video plays, but handle error
get the code from [react-native-video-test](https://github.com/react-native-video/react-native-video-test)

const renderError = () => {
    if (!hasError) {
      return null;
    }

    return (
      <View style={styles.errorContainer}>
        <Image
          resizeMode={'contain'}
          source={{
            uri: 'https://media.istockphoto.com/id/1214467889/video/the-inscription-404-not-found-makes-a-glitch-system-error-motion-graphics.jpg?s=640x640&k=20&c=bipJvdvw02szLppAnxxrZC602tQJDP3jN-O7svgOLfo=',
          }}
          style={styles.errorImage}
        />
      </View>
    );
  };

  const renderLoad = () => {
    if (loading) {
      return (
        <View style={styles.loading}>
          <ActivityIndicator size={'large'} color={colors.text} />
        </View>
      );
    }
  };
  const onLoadStart = () => {
    setLoading(true);
  };

  const onLoadHandler = data => {
    console.log(data, 'opo');
    setLoading(false);
  };

  const onError = e => {
    console.log(e, 'rere');
    console.log('error');
    setHasError(true);
    setLoading(false);
  };

  const bufferConfig = {
    minBufferMs: 100,
    maxBufferMs: 50000,
    bufferForPlaybackMs: 100,
    bufferForPlaybackAfterRebufferMs: 100,
  };
  const isPlay =
    isFocused && !autoplay ? currentIndex !== currentVisibleIndex : true;

  const autoPlayNoActive =
    autoplay === undefined ? true : currentIndex !== currentVisibleIndex;

  const drawerOpen = isDrawerOpen ? true : currentIndex !== currentVisibleIndex;

  return (
    <View style={styles.container}>
      <Video
        style={styles.video}
        ref={primaryRef}
        resizeMode={'contain'}
        controls={true}
        repeat={true}
        paused={isPlay || drawerOpen || autoPlayNoActive}
        rate={1.0}
        onLoadStart={onLoadStart}
        onLoad={onLoadHandler}
        onError={onError}
        progressUpdateInterval={250}
        bufferConfig={bufferConfig}
        source={{
          uri: uri,
        }}
      />
      {renderLoad()}
      {renderError()}
    </View>
  );



<img width="357" alt="Screenshot 2022-11-11 at 01 16 18" src="https://user-images.githubusercontent.com/61016903/201232927-2d5657b9-cc3e-46fc-863b-dda3ffcea93d.png">
<img width="413" alt="Screenshot 2022-11-11 at 01 16 10" src="https://user-images.githubusercontent.com/61016903/201232933-9d8a306d-b7b9-4ca3-9e7f-ae825c48f4cc.png">

**Comment by gizomo** [comment] 2022-12-08 02:37
I faced with that problem at 5.2.1 and v6-alpha3 (tested at tv box).

**Comment by freeboub** [comment] 2023-12-10 20:23
Can you try following patch: https://github.com/react-native-video/react-native-video/pull/3416
It should improve behavior in case of decoder issue

**Comment by freeboub** [comment] 2024-03-12 21:38
To be retested on beta.6

**Closed as completed by freeboub** 2024-03-12 21:38 UTC
Labels: Platform: Android, demo requested
