### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNative.Image.propTypes.resizeMode')

### ISSUE THREAD

**Issue by rStarNarayan** [TheWidlarzGroup/react-native-video#2770] opened 2022-07-15 05:51 UTC
TypeError: undefined is not an object (evaluating '_reactNative.Image.propTypes.resizeMode') its fixed with version 6.0.0 but we are getting below issue 
**Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.**
Configs 
    "react-native": "0.69.1",
    "react": "18.0.0",
    "react-native-video": "6.0.0-alpha.1",

**Comment by CodingMeSwiftly** [comment] 2022-07-15 10:26
Probably a duplicate of https://github.com/react-native-video/react-native-video/issues/2755
See also: https://github.com/react-native-video/react-native-video/issues/2714

**Comment by seckinbrke** [comment] 2022-07-16 11:06
Same issue, I change version with ^6.0.0-alpha.1, but still is same..

**Comment by freeboub** [comment] 2022-08-01 12:33
The fix is already merged here: 847acb75dcbac9af58141cce4d49f9a972ec4f07

If you want, I just backported some known fixes on this branch: https://github.com/react-native-video/react-native-video/pull/2795/files

**Closed as completed** 2022-08-01 12:33 UTC

**Comment by ssiju** [comment] 2022-11-24 14:58
> TypeError: undefined is not an object (evaluating '_reactNative.Image.propTypes.resizeMode') its fixed with version 6.0.0 but we are getting below issue **Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.** Configs "react-native": "0.69.1", "react": "18.0.0", "react-native-video": "6.0.0-alpha.1",

same issue. please help me to fix this issue

**Comment by freeboub** [comment] 2022-11-24 15:57
@ssiju which version of react-native-video?

**Comment by ssiju** [comment] 2022-11-24 16:00
"react-native-video": "^5.2.1"
