### ISSUE TITLE
[Feature]: 2nd subtitle

### ISSUE THREAD

**Issue by hasan-soliev** [TheWidlarzGroup/react-native-video#4029] opened 2024-07-24 08:35 UTC
### Description

if there are 2 subtitles at once it will be very cool

### Why it is needed ?

this is very necessary please

### Possible implementation

Technical POV how to do it

### Code sample

Code sample

**Comment by KrzysztofMoch** [comment] 2024-08-02 15:14
duplicate of #3975

**Closed as not planned by KrzysztofMoch** 2024-08-02 15:14 UTC
Labels: feature
