### ISSUE TITLE
Freeze for 1 second during scroll if setMute changed

### ISSUE THREAD

**Issue by petermjones** [TheWidlarzGroup/react-native-video#1120] opened 2018-07-11 22:29 UTC
### Current behavior
Using RecyclerListView with React Native Video, if you change the mute settings while scrolling, it frequently causes an iPhone to freeze for a second, and then resume scrolling.

### Reproduction steps
Have a scrolling list of videos that play the sound when they are the main visible video, other videos should be muted (they should stop playing video as well).  I'm using RecyclerListView.  Nothing fancy here, the onScroll function determines which video should be playing and if it's changed the screen's state is modified.  The state change, naturally, causes the screen's render function to be called and the video attributes are slightly altered reflecting the state.

### Expected behavior
Smooth, uninterrupted scrolling.

### Platform
I'm using iOS 11.2.6

Our internal notes:
React Native Video performance enhancement July 11, 2018, so far only tested on iOS.
XCode search for file RCTVideo.m, replace setMuted function:

- (void)setMuted:(BOOL)muted
{
  _muted = muted;
  // [self applyModifiers]; // this caused the 1 second delay when scrolling

  if (_muted) {
    [_player setVolume:0];
    [_player setMuted:YES];
  } else {
    [_player setVolume:_volume];
    [_player setMuted:NO];
  }
}

**Comment by cobarx** [comment] 2018-08-06 01:40
This is a duplicate of #1067. I'll have to see about merging the fix we have in #1113, but we need a better long term fix.

**Closed as completed by cobarx** 2018-08-06 01:40 UTC
