### ISSUE TITLE
[BUG]: View Transform rotate not affect to the video

### ISSUE THREAD

**Issue by rayhanmhd123** [TheWidlarzGroup/react-native-video#4036] opened 2024-07-26 09:27 UTC
### Version

6.4.3

### What platforms are you having the problem on?

Android

### System Version

Android 14

### On what device are you experiencing the issue?

Simulator

### Architecture

New architecture with interop layer

### What happened?

When view use transform, the video does not transform.

### Reproduction

repository link

### Reproduction

This example code i use. when use image it can be rotate, if using video does not rotate.

import React, {useEffect, useRef} from 'react';
import { Image, View } from 'react-native';
import SplashScreen from 'react-native-splash-screen';
import Video, {VideoRef} from 'react-native-video';

function App(): React.JSX.Element {
  const videoRef = useRef<VideoRef>(null);

  useEffect(() => {
    SplashScreen.hide();
  }, []);

  return (
    <View style={{transform: [{rotate: '90deg'}]}}> 
      <Video
        ref={videoRef}
        hideShutterView={false}
        shutterColor="transparent"
        source={require('./src/asset/videoplayback.mp4')}
        onError={(e: any) => {
          console.error(e);
        }}
        repeat={true}
        style={{height: '50%', width: '50%'}}
        resizeMode={'contain'}
      />
      <Image
        source={{
          uri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Steilk%C3%BCste_bei_Ahrenshoop.jpg/800px-Steilk%C3%BCste_bei_Ahrenshoop.jpg',
        }}
        resizeMode="contain"
        style={{width: '50%', height: '50%'}}
      />
    </View>
  );
}

export default App;

**Comment by rayhanmhd123** [comment] 2024-07-26 15:43
i notice the bug since version 6.2.0

**Comment by mlecoq** [comment] 2024-07-26 19:18
Did you try `useTextureView` ?

**Comment by rayhanmhd123** [comment] 2024-07-27 06:14
I've tried it and it worked, but isn't that function deprecated?

**Comment by mlecoq** [comment] 2024-07-27 07:33
Yes because it has been replaced by viewType, but there is a bug on it:

See https://github.com/TheWidlarzGroup/react-native-video/issues/4030

**Comment by rayhanmhd123** [comment] 2024-07-28 09:02
okay, thank you. i close the issue

**Comment by seyedmostafahasani** [comment] 2024-07-28 10:16
@rayhanmhd123 please re-open the issue. Wait for the merge before closing.

**Comment by rayhanmhd123** [comment] 2024-07-28 10:21
okay, thank you all for your support

**Comment by jspizziri** [comment] 2024-07-31 12:28
I just want to chime in and say that I manually applied a patch file matching the PR referenced above and with `viewType={ViewType.TEXTURE}` my issue is resolved. If anyone is too anxious to wait for the above PR to be merged and released I've attached the patch file here.

[react-native-video-npm-6.4.3-45cb372a44.patch](https://github.com/user-attachments/files/16441760/react-native-video-npm-6.4.3-45cb372a44.patch)

**Comment by KrzysztofMoch** [comment] 2024-08-02 11:12
Fix will be released in `6.4.4`

**Closed as completed by KrzysztofMoch** 2024-08-02 11:12 UTC
Labels: bug

**Comment by fendermany** [comment] 2025-07-23 09:31
started reproducing by v.6.16.1 (v.6.16.0 - I haven't tested it, but I guess it's broken there. ) works without problems with 6.15.0.
