### ISSUE TITLE
Video hangs/stalls often

### ISSUE THREAD

**Issue by dojiboy9** [TheWidlarzGroup/react-native-video#263] opened 2016-07-04 21:14 UTC
Hi,

I am using react native video to play MP4 videos. These videos are sent from a server (I.e. They are non local) and are no large than 5MB in size on average.

I'm pretty sure the loading time is fine as I'm getting the onLoad event, and the videos start playing. However, the videos tend to freeze often. I have to pause/play them to get them going again. I don't think it's a streaming / internet issue (because I think the videos are loaded entirely), so I think it might be an issue on the mobile side.

Is anyone else seeing something like this? Any help would be welcome.

**Comment by mattapperson** [comment] 2016-08-29 13:05
Can you provide any sample code to allow us to reproduce the issue?

**Comment by mattapperson** [comment] 2016-08-30 03:04
Dupe of #303

**Closed as completed by mattapperson** 2016-08-30 03:04 UTC
