### ISSUE TITLE
Must stop iOS 10 animated scaling to fill

### ISSUE THREAD

**Issue by JBerendes** [TheWidlarzGroup/react-native-video#331] opened 2016-09-19 17:42 UTC
To Reproduce:
- use a video that is smaller than the container it will fill
- load and immediately start playing the video

Outcome:
- The video quickly and in an animated way(as if it were zooming in) scales up to fill the space

Preferred: Off by default. Only scale the video to fill when a property has been passed.

Related issue #297

**Comment by mattapperson** [comment] 2016-10-06 21:38
Closing as dupe of #330

**Closed as completed by mattapperson** 2016-10-06 21:38 UTC
Labels: bug, help wanted, Platform: iOS
