### ISSUE TITLE
Crash App When set Url  Platform IOS

### ISSUE THREAD

**Issue by memberwebm** [TheWidlarzGroup/react-native-video#3043] opened 2023-02-23 08:01 UTC
Could you help me? When i get url in sever and set url on uri react native video, it be crashed app

https://user-images.githubusercontent.com/110653846/220851237-991e004c-60d3-4652-9d13-efbb28a0beef.mov

<img width="859" alt="Screenshot 2023-02-23 at 15 01 38" src="https://user-images.githubusercontent.com/110653846/220851297-f924bb58-5075-4f2a-85a1-75b059d12f2e.png">

**Comment by vargajacint** [comment] 2023-02-24 08:25
@memberwebm Could you print the 'url' to check is it valid or not. Also 'onLoad', 'onProgress' callback could cause your crash. Could you share those as well?

**Comment by freeboub** [comment] 2023-02-25 09:28
No version provided, no sample, no reason to incriminate RNV, let's close this ticket

**Closed as not planned** 2023-02-25 09:28 UTC

**Comment by memberwebm** [comment] 2023-02-28 03:31
> No versio
<img width="562" alt="Screenshot 2023-02-28 at 10 30 10" src="https://user-images.githubusercontent.com/110653846/221746261-a8f985b4-0266-43c2-8c35-ddc88f40b468.png">
n provided, no sample, no reason to incriminate RNV, let's close this ticket
<img width="808" alt="Screenshot 2023-02-28 at 10 30 34" src="https://user-images.githubusercontent.com/110653846/221746308-988c2f3a-af3a-477e-81c7-5c28bc036c55.png">
This is my onProgress and onLoad @freeboub

**Comment by freeboub** [comment] 2023-02-28 14:05
Please provide the crash description. The logcat or the js callstack...

**Comment by memberwebm** [comment] 2023-03-01 06:46
<img width="1007" alt="Screenshot 2023-03-01 at 13 46 23" src="https://user-images.githubusercontent.com/110653846/222064692-2910ee8c-cd58-4428-9a11-698bd7358c43.png">
please, help me :(

**Comment by vargajacint** [comment] 2023-03-01 06:55
@memberwebm Just think about it. How we would help you without knowing your whole code. 
Please provide it and I will try to figure out what is wrong.
Also, if you start your application from xCode, after the crash you have some logs in your xCode.

**Comment by memberwebm** [comment] 2023-03-01 07:45
<img width="558" alt="Screenshot 2023-03-01 at 14 43 45" src="https://user-images.githubusercontent.com/110653846/222075797-7334bc39-6c60-403d-a3ce-d34c3dbafc6b.png">
<img width="1133" alt="Screenshot 2023-03-01 at 14 44 35" src="https://user-images.githubusercontent.com/110653846/222075810-d0081763-c114-48d6-b3d6-90d04cfe179d.png">
FIRST: I get url from sever,

**Comment by vargajacint** [comment] 2023-03-01 07:50
1. Can you provide the `url` to check wether is it valid or not?
2. Can you provide the whole code? It looks like you have a couple of other callbacks, maybe it's easier to debug.
3. Can you reproduce this issue in a simplified public repository?

**Comment by memberwebm** [comment] 2023-03-01 07:58
this is url video : https://rr3---sn-npoeenll.googlevideo.com/videoplayback?expire=1677679026&ei=UgX_Y4-zNqae4t4P04WdwA8&ip=13.213.66.17&id=o-AGyH3zxCyOu-TSc9XrxZqGdo2QDYYMgWwMC7a2-V5lXe&itag=18&source=youtube&requiressl=yes&mh=A0&mm=31%2C26&mn=sn-npoeenll%2Csn-30a7rne6&ms=au%2Conr&mv=m&mvi=3&pl=23&ctier=SH&initcwndbps=703750&spc=H3gIhkvVLOLinFsuxY35p6pnR7L45jA&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=2412863&ratebypass=yes&dur=32.320&lmt=1677576004044210&mt=1677657213&fvip=2&fexp=24007246&c=ANDROID&txp=5530434&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cctier%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRgIhANoHI_7uMIG2leWfZN2tr7IIPpv_Hox1Ue044zaiDrFPAiEAp9WcoxxK1vyTMuEeSK_nakV73_b08dmZ5WoDXHHT6lQ%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgAr6fuhIw7ZiQ4Hwrn04CPsYfQFdtY3rY_fIFgAYZrjgCIQChyCs-bWsNX7P0k1XVauQ7DklYp8V1Xj8bPs0RHtmw0w%3D%3D

**Comment by vargajacint** [comment] 2023-03-01 08:21
As I saw, this url use redirection. Maybe, it could cause your error. Could you hardcode this url into and example repository?

**Comment by memberwebm** [comment] 2023-03-01 08:27
yes i harcore, it work but when use url from sever i been crashed app

**Comment by memberwebm** [comment] 2023-03-01 09:53
<img width="1312" alt="Screenshot 2023-03-01 at 16 51 55" src="https://user-images.githubusercontent.com/110653846/222104523-3d0a9d73-7075-4dde-95f2-aea8a71379ac.png">
@vargajacint  I edited the code to be more concise, can you help me?

**Comment by vargajacint** [comment] 2023-03-01 10:01
Okey, let's start from the beginning. 
1. Which version of react-native-video are you using?
2. Check your code without any business logics. Particularly render just the `Video` component with a hardcoded video url. Is it still crashing?
3. Wrap your async code with `try...catch` block, and log the caught error.

For testing purpose use this video url: http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
