### ISSUE TITLE
[BUG]: Android kotlin version mismatched

### ISSUE THREAD

**Issue by mansiRadicalRack** [TheWidlarzGroup/react-native-video#4015] opened 2024-07-17 11:04 UTC
### Version

6.0.0

### What platforms are you having the problem on?

Android

### System Version

Android

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

[Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.0.0, expected version is 1.7.1]

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
in react native execution part

**Comment by KrzysztofMoch** [comment] 2024-07-18 07:32
Duplicate of https://github.com/TheWidlarzGroup/react-native-video/issues/4009

**Closed as not planned by KrzysztofMoch** 2024-07-18 07:32 UTC
Labels: bug
