### ISSUE TITLE
iOS recorded video is not playing in android device?

### ISSUE THREAD

**Issue by yogeshj-aloha** [TheWidlarzGroup/react-native-video#1912] opened 2020-02-17 10:12 UTC
I am not able play iOS device recorded video in android phone using react-native

Its play in iOS but play in android
Extension is : .mov for iOS and .mp4 for android

**Comment by benoitdion** [comment] 2020-02-17 16:59
Closing as duplicate of #1911

**Closed as completed by benoitdion** 2020-02-17 16:59 UTC
