### ISSUE TITLE
How to replay a video by clicking on an external button?

### ISSUE THREAD

**Issue by afilp** [TheWidlarzGroup/react-native-video#877] opened 2017-12-18 10:41 UTC
I use `seek(0)` to replay a video that played once and finished, when clicking on a button.

But `seek(0)` just sends the video to start and does not play it. This is OK, but where is a method called `play()` to make it start playing again?

Note that I have `repeat={false}`.

**Comment by selsamman** [comment] 2018-01-02 10:28
This is an unfortunate limitation.  I have heard it suggested that you can toggle pause but this is really hacky trying to make sure the component renders.  The other thing you can do is to use key prop with a sequence number to force the component to reload.  Another thought is to use repeat={true} and handle the onEnd event to pause the video and then toggle your pause state with the play button.  None of these are pretty.

**Comment by djw27** [comment] 2018-01-02 11:15
Something similar to the following works for us: 

```
replayVideo = () => {
    this._video && this._video.seek(0);
    this.setState({ videoPaused: false });
}

...

render() {
    return (
        <Video
            ref={component => (this._video = component)}
            paused={videoPaused}
            ... 
        />
    );
}
```

**Comment by afilp** [comment] 2018-01-12 01:04
@selsamman @djw27 Thanks! The combined `paused` and ``onEnd`` trick did work. Still a trick though, took time to research this, it would be nice if this could be implemented as a 'replay' method.

Note that I did not need to use `repeat`, just 'paused' the video at the very end through a `setState` invocation. Not sure why it works since it does not repeat to have the need for a "pause", but it works for our use case of "replaying on button press".

````
paused={this.state.isVideoPaused}    // This is ``falsy`` initially
repeat={false}                
onEnd={() => this.setState({isVideoPaused: true})}    
````

And then, as you suggested, this:

````
    playVideo() {
        this.refVideoPlayer && this.refVideoPlayer.seek(0);
        this.setState({isVideoPaused: false});
    }
````



Thanks again.

**Comment by Charpell** [comment] 2021-08-18 22:05
Thanks @afilp , works like charm

**Comment by kapeed8** [comment] 2021-09-19 17:29
we need to handle from 2 place 1st is **setPause = true on onEnd** event then make **setPause = false on onReadyForDisplay**

 <Video
.....
.....
onEnd={() => {
            setReachedatEnd(true);
            overlayTimer.current = null;
            setOverlay(true);
            setPause(true);
          }}
onReadyForDisplay={() => {
            setBuffering(false);
            setPause(false);
          }}
/>

**This solution for onBuffer event not firing** 

try to do
add react-native.config.js file at root folder
then add following code

**module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
};**

Goto android folder
**cd android** 

then run follwing command in cmd
**gradlew clean**

**Comment by freeboub** [comment] 2022-06-03 20:36
Seems like a very old topic.
I am not able to reproduce the issue on sample.
Let's close this ticket and reopen it if needed

**Closed as completed by freeboub** 2022-06-03 20:36 UTC
Labels: discussion
