### ISSUE TITLE
[Feature]: New architecture support

### ISSUE THREAD

**Issue by maksymhcode-care** [TheWidlarzGroup/react-native-video#4273] opened 2024-11-05 11:02 UTC
### Description

Do you have any idea or timefrime on when we expect new architecture support?

### Why it is needed ?

Something like video player would greatly benefit from jsi and fabric support

**Comment by KrzysztofMoch** [comment] 2024-11-05 15:21
So react-native-video v6 is unlikely to get new architecture support (but never say never). For now v6 should work with [Interop Layer](https://github.com/reactwg/react-native-new-architecture/discussions/135). 

We have started working on v7, that will be complete rework of library - it will support both Old and New Architecture. 
You can see PoC demo here https://x.com/krzysztof_moch/status/1844271280167714874

Also this is duplicate of https://github.com/TheWidlarzGroup/react-native-video/issues/2650, so I will close this one

**Closed as not planned by KrzysztofMoch** 2024-11-05 15:21 UTC
Labels: feature

**Comment by maksymhcode-care** [comment] 2024-11-07 15:23
> So react-native-video v6 is unlikely to get new architecture support (but never say never). For now v6 should work with [Interop Layer](https://github.com/reactwg/react-native-new-architecture/discussions/135).
> 
> We have started working on v7, that will be complete rework of library - it will support both Old and New Architecture. You can see PoC demo here https://x.com/krzysztof_moch/status/1844271280167714874
> 
> Also this is duplicate of #2650, so I will close this one

What can we expect from v7? except support for Old and New Architecture

**Comment by nikhiltekwani09** [comment] 2025-03-18 17:53
@KrzysztofMoch is it working with interop layer for you?
