### ISSUE TITLE
react-native-video is not playing in video in the flatList while single video outside flatlist is playing

### ISSUE THREAD

**Issue by yadavmurari111** [TheWidlarzGroup/react-native-video#2794] opened 2022-08-01 11:35 UTC
I am using [react-native-video](https://github.com/react-native-video/react-native-video) in my sample project to render videos in the flatlist. problem i am facing is video items are not playing in flatlist when i put same video component outside flatlist , it is working fine. Also i did flatlist optimization accordingly . please help me out.

**Comment by freeboub** [comment] 2022-08-03 07:17
Duplicate of: https://github.com/react-native-video/react-native-video/issues/2668

**Closed as completed by freeboub** 2022-08-03 07:17 UTC
