### ISSUE TITLE
[IOS] Freeze and Crash app

### ISSUE THREAD

**Issue by thaiphamvan** [TheWidlarzGroup/react-native-video#3034] opened 2023-02-13 06:49 UTC
# Bug
 I run on my app and see an error :(
 Step 1: Reload the app by terminal (Press R key on the terminal)
 Step 2: App State : Foreground -> background -> Foreground
 Step 3: App Freeze and crash

## OS: 
"react-native": "0.68.2",
"react-native-video": "^5.2.1",
## Some Informations
- Error on the Sentry : Rendered fewer hooks than expected. This may be caused by an accidental early return statement
- I checked my code and use method of Hook on the top function and without if/else.

**Comment by MinhThu100200** [comment] 2023-02-15 02:57
I have same issue. Please let me know if you find a solution.

**Comment by memberwebm** [comment] 2023-02-23 09:42
I have same issue. Please let me know if you find a solution.

**Comment by vargajacint** [comment] 2023-02-24 08:56
Is this problem can re-produce on a released version as well?
@thaiphamvan @MinhThu100200  @memberwebm

**Comment by BraveEvidence** [comment] 2023-03-09 14:08
This will help https://www.youtube.com/watch?v=vVI7ZAZq5e0

**Comment by freeboub** [comment] 2023-04-06 13:25
any logs ? any reproduction on V6 version ?

**Comment by minh-dai** [comment] 2023-07-28 03:20
android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false

Env:
Android 12,
"react-native-video": "5.0.2",

**Comment by Mansigupta-Playleap** [comment] 2023-11-01 05:15
any update?

**Comment by freeboub** [comment] 2024-06-11 20:05
Issue on 5.2, no feedback for now. let's close this issue

**Closed as completed by freeboub** 2024-06-11 20:05 UTC
Labels: Platform: iOS, demo requested
