### ISSUE TITLE
[BUG]: IOS preroll ads issue

### ISSUE THREAD

**Issue by Ibad9** [TheWidlarzGroup/react-native-video#3894] opened 2024-06-11 11:15 UTC
### Version

6.0.0

### What platforms are you having the problem on?

iOS

### System Version

IOS

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

play any video with adtag url containing preroll ads. On android the ad will play perfectly and then the video will play. But on IOS the video plays for almost 2 seconds then ad plays and then video plays again. It should play the ad fist then play video on IOS too as on Android.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 

Play any video just add preroll adtagUrl.

**Comment by freeboub** [comment] 2024-06-11 14:06
I close the issue as duplicate of: https://github.com/TheWidlarzGroup/react-native-video/issues/3114
There is a workaround in this ticket (even if I don't like it)

**Closed as completed by freeboub** 2024-06-11 14:06 UTC
Labels: bug
