### ISSUE TITLE
[Android] Updating selectedTextTrack does not work

### ISSUE THREAD

**Issue by enisit** [TheWidlarzGroup/react-native-video#2892] opened 2022-10-17 15:38 UTC
# Bug
Updating  `selectedTextTrack` with type "language" | "title" | "index" always selects first textTrack from the array. 

## Platform
Android

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 219.58 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2022.09.26.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.3

## Steps To Reproduce

1. Add two or more elements as `textTracks` prop
2. Add state variable `selectedTextTrack` with initial value of `{type: 'disabled'}` as prop
3. Update `selectedTextTrack` with value `{type: 'index', value: 1}`. It will show proper textTrack
4. Update `selectedTextTrack` with value `{type: 'index', value: 0}`. It again shows proper textTrack
5. Set `selectedTextTrack` back to value `{type: 'index', value: 1}`. It won't work, it still shows textTrack with index 0.
6. From now on, setting `selectedTextTrack` won't change the shown textTrack except `{type: 'disabled'}`. Setting value of `selectedTextTrack` to any other type or value always shows textTrack that is first in the array of `textTracks`(the one with index value of 0)

## Expected behaviour

Video should always show `textTrack` specified by  `selectedTextTrack` prop. 

## Reproducible sample code

```
import React, { useEffect, useState, useRef } from 'react';
import {
  Button,
  StyleSheet,
  Text,
  View,
  useWindowDimensions,
  StatusBar,
  TouchableOpacity,
} from 'react-native';
import Video, { TextTrackType, OnProgressData } from 'react-native-video';
import Ionicons from '@expo/vector-icons/Ionicons';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';

interface TextTrack {
  type: 'index' | 'system' | 'disabled' | 'title' | 'language';
  value?: string | number | undefined;
}

const VideoScreen = () => {
  const layout = useWindowDimensions();
  const videoRef = useRef<Video>(null);
  const [currentTime, setCurrentTime] = useState<number>(0);
  const [paused, setPaused] = useState<boolean>(true);
  const [selectedTextTrack, setSlectedTextTrack] = useState<TextTrack>({
    type: 'disabled'
  });
 
  useEffect(() => {
    console.log('Track: ', selectedTextTrack);
  }, [selectedTextTrack]);

  return (
    <View
      style={{ width: layout.width, height: layout.height, backgroundColor: 'black' }}
    >
      <StatusBar hidden />
      <Video
        ref={videoRef}
        onLoadStart={() => console.log('Started')}
        onError={console.log}
        style={{ width: layout.width, height: layout.height }}
        onLoad={console.log}
        progressUpdateInterval={1000}
        paused={paused}
        textTracks={[
          {
            type: TextTrackType.VTT,
            title: 'Spanish',
            language: 'es',
            uri: 'https://pathToTheFile_esp.vtt',
          },
          {
            type: TextTrackType.VTT,
            title: 'English',
            language: 'en',
            uri: 'https://pathToTheFile_eng.vtt',
          },
        ]}
        selectedTextTrack={selectedTextTrack}
        source={{
          uri: 'https://pathToTheVideo.mp4',
        }}
      />
      <View style={styles.controls}>
        <View style={styles.playControls}>
          <TouchableOpacity
            onPress={() => {
              seekByStep(true);
            }}
          >
            <MaterialIcons name="replay-10" color="white" size={50} />
          </TouchableOpacity>
          <TouchableOpacity
            onPress={() => {
              setPaused(!paused);
            }}
          >
            <Ionicons name={paused ? 'play' : 'pause'} color="white" size={50} />
          </TouchableOpacity>
          <TouchableOpacity
            onPress={() => {
              seekByStep();
            }}
          >
            <MaterialIcons name="forward-10" color="white" size={50} />
          </TouchableOpacity>
        </View>
        <View style={{ position: 'absolute', top: 10, right: 10, flexDirection: 'row' }}>
          <TouchableOpacity
            style={[
              styles.cc,
              {
                backgroundColor: selectedTextTrack?.value === 1 ? 'red' : 'white',
              },
            ]}
            onPress={() => setSlectedTextTrack({ type: 'index', value: 1 })}
          >
            <Text>EN</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[
              styles.cc,
              {
                backgroundColor: selectedTextTrack?.value === 0 ? 'red' : 'white',
              },
            ]}
            onPress={() => setSlectedTextTrack({ type: 'index', value: 0 })}
          >
            <Text>ES</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[
              styles.cc,
              {
                backgroundColor: selectedTextTrack?.type === 'disabled' ? 'red' : 'white',
              },
            ]}
            onPress={() => setSlectedTextTrack({ type: 'disabled' })}
          >
            <Text>OFF</Text>
          </TouchableOpacity>
        </View>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  controls: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
  },
  playControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginHorizontal: 30,
  },
  cc: {
    padding: 10,
    marginHorizontal: 10,
  },
});

export default VideoScreen;
```

PS. We use Expo project with Managed Flow and `expo-dev-client` but it should not make any difference. On iOS everything works fine.

**Comment by valeri-terziyski** [comment] 2022-10-24 15:46
I can confirm I'm also seeing this.

**Comment by freeboub** [comment] 2022-10-29 13:24
Can you have a look to this PR, it may fixe the issue: https://github.com/react-native-video/react-native-video/pull/2806

**Comment by freeboub** [comment] 2024-03-29 17:00
multiple fixes done since > 1 years, let's close this issue (to be retested on 6.0.0-beta.7)

**Closed as completed by freeboub** 2024-03-29 17:00 UTC
Labels: help wanted, Platform: Android
