### ISSUE TITLE
[BUG]: ResizeMode does not apply after the second play onwards when props repeat true

### ISSUE THREAD

**Issue by krisnapy** [TheWidlarzGroup/react-native-video#3929] opened 2024-06-21 04:43 UTC
### Version

6.1.2

### What platforms are you having the problem on?

Android

### System Version

Android 13

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

ResizeMode does not apply after the second play onwards when props repeat true.

https://github.com/TheWidlarzGroup/react-native-video/assets/96037957/d4c4204d-14fc-47a3-ab58-8719f0aaf78d

```
import React from 'react'
import Video, { ResizeMode } from 'react-native-video'

import { LandingScreenProps } from './types'

export const LandingScreen: LandingScreenProps = () => {
  return (
    <Video
      source={{ uri: "https://d1c40hpuz0tre6.cloudfront.net/stories/01HZRFTRYCM19PZ49BE54Z4FSY.mp4" }}
      style={{ flex: 1 }}
      resizeMode={ResizeMode.COVER}
      controls
      repeat
    />
  )
}
```

### Reproduction

Step to reproduce this bug are: 
1. Play video with props repeat true.

**Comment by freeboub** [comment] 2024-06-24 10:49
I don't reproduce the issue with the sample included in the repo.
Can it be caused by the {flex: 1} usage ?
BTW, I found an ugly resize blink when repeating the playback

**Comment by krisnaItsAVirus** [comment] 2024-06-24 11:48
Do you try with my code? After I tried with other videos, it did not happen with some videos.

**Comment by krisnapy** [comment] 2024-06-24 11:50
Have you tried with my code or video source? Because I tried with other video sources, it did not happen with some of the videos.

**Comment by freeboub** [comment] 2024-06-24 13:11
Your video have problems, I cannot read it correctly on VLC ...
But you try to remove the flex: 1 ?

**Comment by gabrielsalvi** [comment] 2024-06-24 19:13
The same is happening with me too.

Version 6.2.0
Android 13

**Comment by moskalakamil** [comment] 2024-07-12 13:37
Hi @krisnapy @gabrielsalvi, I've implemented a fix for this issue. You can see the changes in the latest pull request #4000

**Closed as completed** 2024-07-15 08:15 UTC
Labels: bug, Platform: Android
