### ISSUE TITLE
play hls on wrong rctvideo.m line384 ios 10

### ISSUE THREAD

**Issue by neegqi** [TheWidlarzGroup/react-native-video#424] opened 2016-12-19 13:52 UTC
`  if([keyPath isEqualToString:playbackRate]) {
          self.onPlaybackRateChange(@{@"playbackRate": [NSNumber numberWithFloat:_player.rate],
                                      @"target": self.reactTag});
          if(_playbackStalled && _player.rate > 0) {
              self.onPlaybackResume(@{@"playbackRate": [NSNumber numberWithFloat:_player.rate],
                                      @"target": self.reactTag});
              _playbackStalled = NO;
          }
      }`

**Comment by hellogerard** [comment] 2016-12-23 20:50
🤔

**Comment by XHTeng** [comment] 2016-12-27 05:45
iPhone 5 iOS10, has the crash

**Comment by smkhalsa** [comment] 2017-01-03 04:25
I'm also getting this on iPhone 5 simulator. Anyone track this down yet?

**Comment by hellogerard** [comment] 2017-01-03 15:50
This is a dupe of #421 and should be closed.

**Closed as completed** 2017-02-09 17:52 UTC
