### ISSUE TITLE
App crashes on ios v17.2.1

### ISSUE THREAD

**Issue by mohamedmagdy7** [TheWidlarzGroup/react-native-video#3463] opened 2024-01-08 14:46 UTC
# Bug
App crashes on ios v17.2.1 when navigating away from a screen that have a video on it.

## Platform
Which player are you experiencing the problem on:
* iOS
![IMG_4031](https://github.com/react-native-video/react-native-video/assets/98698005/1082d779-b29e-4d5b-9454-afed2af39366)

## Environment info

Library version: 5.2.1
Device: iOS v17.2.1

## Steps To Reproduce

1. Open video component on ios phone with ios version 17.2.1
2. Navigate away from video component to other screen
...

## Expected behaviour

1. App works normally

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by KrzysztofMoch** [comment] 2024-01-08 17:07
Duplicate of https://github.com/react-native-video/react-native-video/issues/3407 (Upgrade react-native-screen to `3.29.0` should do the job)

**Closed as not planned by KrzysztofMoch** 2024-01-08 17:07 UTC
