### ISSUE TITLE
[Feature]: How to Implement FFmpeg with React Native Video?

### ISSUE THREAD

**Issue by gbebri** [TheWidlarzGroup/react-native-video#4221] opened 2024-10-07 09:37 UTC
### Description

I’m working on a React Native app that uses the react-native-video library for video playback. I would like to implement FFmpeg to manipulate video streams (e.g., transcoding, trimming, etc.) within the app. Is there a recommended approach to integrate FFmpeg functionality alongside react-native-video?

### Why it is needed ?

I need FFmpeg functionality in my React Native app to manipulate video streams directly within the app.

**Comment by freeboub** [comment] 2024-10-08 19:37
duplicate of https://github.com/TheWidlarzGroup/react-native-video/issues/3106

**Closed as completed by freeboub** 2024-10-08 19:37 UTC
Labels: feature
