### ISSUE TITLE
com.yqritc.scalablevideoview.ScalableVideoView.reset:  DASH not playing on Android, Exoplayer Crashes the app, HLS freezes the app. 

### ISSUE THREAD

**Issue by YoucefBen47** [TheWidlarzGroup/react-native-video#3098] opened 2023-04-17 14:20 UTC
# Bug

Which player are you experiencing the problem on:
* Android

## Environment info

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 64.86 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.8.0 - /opt/homebrew/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.2.1

## Expected behaviour

1. DASH url plays on Android.
2.HLS urls plays on Android.

## Reproducible sample code

We are using the player to play short videos. DASH urls do not work on Android. We are using HLS videos but when we click to navigate to another screen the app freezes and we get this log in the ANRs console:

com.yqritc.scalablevideoview.ScalableVideoView.reset
  #05  pc 0x000000000004a044  /system/lib64/libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+180)
This Binder call may be taking too long, causing the main thread to wait, and triggering the ANR.

We tried exoplayer before but the app started crashing on some phones.

**Comment by freeboub** [comment] 2023-04-17 14:51
You need to try with exoplayer implementation ...
The mediaPlayer version is deprecated

**Comment by YoucefBen47** [comment] 2023-04-17 14:54
@freeboub Thank you for replying. We did try exoplayer like I mentioned and that caused the app to crash on some devices.

**Comment by freeboub** [comment] 2023-04-29 12:02
The crash seems to be linked to scalablevideoview ... No idea on how to handle that.
Anyway as MediaPlayer implementation has drop on V6, I will close the issue.
if you can reproduce your crash issue on V6, it would be interesting to fix it !

**Closed as completed by freeboub** 2023-04-29 12:02 UTC
Labels: Platform: Android, V5
