### ISSUE TITLE
Video poster disappears after putting app in background for audio files

### ISSUE THREAD

**Issue by jrhager84** [TheWidlarzGroup/react-native-video#2800] opened 2022-08-03 06:37 UTC
# Bug

poster disappears with audioOnly after app goes into background

## Platform
iOS & Android
Which player are you experiencing the problem on:
* iOS
* Android

## Environment info

React native info output:

```bash
 System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.70 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.1 - /opt/homebrew/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /opt/homebrew/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.0

## Steps To Reproduce

1. Instantiate a Video with just audio.
2. Set poster
3. Put app in background
4. Go back into app

## Expected behaviour

1. Poster should remain

**Comment by freeboub** [comment] 2022-08-20 13:22
Poster management is fully done in JS (see Video.js file).
By reviewing the code I don't find the root cause, but I am sure you can find it ! :) ( and provide a pull request to fix it :D )

Edit: do you use the audioOnly prop ?

**Comment by freeboub** [comment] 2024-04-02 21:09
I removed audioOnly prop as it bring unexpected JS code ...
I advise to move poster management on application side to ensure the behavior is the expected one with your app

**Comment by freeboub** [comment] 2024-04-05 08:36
linked PR merged, let's close this issue

**Closed as completed by freeboub** 2024-04-05 08:36 UTC
Labels: bug
