### ISSUE TITLE
Why does the app become slow on Andriod when I use react-native-video?

### ISSUE THREAD

**Issue by xts-bit** [TheWidlarzGroup/react-native-video#3218] opened 2023-08-27 12:16 UTC
Why does the app become slow on Andriod when I use react-native-video? The prop.video is a local file URL, I'm using React Native new arch With the latest version of react-native-video ^6.0.0-alpha.7. On iOS I noticed it's OK. But on Andriod both emulator and real device. It's not smooth as other apps like TikTok and Instagram are when is comes to video. 

```
import { Dimensions, StyleSheet, View } from 'react-native'
import React from 'react'
import Video from 'react-native-video';

type Props = {
  video: string
}

const { height, width } = Dimensions.get('window');

const Video = (props: Props) => {

  return (
    <View style={{ backgroundColor: 'gray' }}>
      <Video
        source={{ uri: props.video }}
        resizeMode="cover"
        repeat
        paused={true}
        style={styles.backgroundVideo} />
    </View>
  );
}

export default Video;

const styles = StyleSheet.create({
  backgroundVideo: {
    height,
    width,
  },
});
```

**Comment by freeboub** [comment] 2023-09-03 12:57
@xts-bit can you please be more explicit in the feature description ?
Documentation specify following possibility which should match your expectation:
source={{ uri: 'file:///sdcard/Movies/sintel.mp4' }}
but maybe it doesn't work anymore.

which platform did you test ?
which path do you need to use ?

**Comment by xts-bit** [comment] 2023-09-03 13:35
@freeboub I tried for iOS, However, can you please tell me Why it's super slow on Andriod? I can see  Configure project :react-native-video
useExoplayerIMA:true

**Comment by freeboub** [comment] 2023-09-03 13:55
> @freeboub I tried for iOS, However, can you please tell me Why it's super slow on Andriod? I can see  Configure project :react-native-video
> useExoplayerIMA:true
> 

Please update the ticket description to explain what you tested.

I cannot identify what is slow on your side without a deep analysis... Please open a ticket explaining your seeing. What you tested. Ensuring network is Ok. Server is ok. Ui doesn't interfere with react native video. And reproduce the issue on a sample!

**Comment by xts-bit** [comment] 2023-09-03 14:15
@freeboub Please check my edited issue :)

**Comment by freeboub** [comment] 2023-09-03 14:34
Thank you, but don't mix both issues...

Video with a path and performances shall be handled in different tickets.

**Comment by xts-bit** [comment] 2023-09-03 14:56
@freeboub I don't know if that local file path is really a issue because i think i used the react-native-fs the wrong way for caching the video, However now it can able to load file from a local file URL for both Andriod and iOS. 

For performance issue yes it a problem, And unfortunately i mixed it so now what should i do open a new issue?

**Comment by freeboub** [comment] 2023-09-03 16:01
No that is ok to continue with this one if there is no issue with file path! Thank you.

A question, did you try to :
- use a network url ? ( the goal is to identify if the issue comes from local file playback) 
- comment all on* callbacks from react native video ? (identify you do too much work (state update,... ) during playback. The onProgress callback is called very often by default for exemple.

**Comment by freeboub** [comment] 2023-09-03 16:03
Reviewing again, and new arch is not supposed to work with react native video.
There is PR opened to support it 🤔

**Comment by xts-bit** [comment] 2023-09-09 13:56
@freeboub Olivier, I'm sorry! I just got the notification from a comment,
1: Use I tried to use a remote network URL, But I didn't need any difference between the local file path vs. network URL
2: I see Yes I'm on an older arch, I thought new React native projects were in the new arch by default, I'm sorry my bad. 

However, one thing I forgot to share with you is that The videos are displaying like YouTube shorts in a flash-list, And it lags when I move one video to another. So thinking in that case what can be the issue?    

Wish you an amazing weekend!

**Comment by freeboub** [comment] 2023-09-09 14:19
Ok, thank you for the update!
Do you umount or stop videos correctly when they are out of screen?
When I say stop, I mean give an undefined source to <Video.

**Comment by xts-bit** [comment] 2023-09-09 14:25
@freeboub I guess here I'm wrong! Because currently, I'm just pausing the video according to their index and current index values. Like if the current index is not equal to the index then pause.

**Comment by freeboub** [comment] 2023-09-09 15:26
@xts-bit with pause you should also encounter some decoder issue on some android device. Let me know if it works

**Comment by xts-bit** [comment] 2023-09-09 15:30
@freeboub Yep, So is there any way to kill the video? Let me try this killing approach and see how things work.

**Comment by freeboub** [comment] 2023-09-09 17:10
@xts-bit not sure what you call 'killing' but setting the source to undefined should stop playback. If you unmount the component it should completely deallocate the video

**Comment by xts-bit** [comment] 2023-09-10 09:04
By Killing I mean completely deallocating the video so it won't even load, I tried to implement this approach but it's hard to implement this in my codebase it disturbs the code logic.

I wish there was any prop that automatically does that. or any package like react-native-fast-video :)

**Comment by freeboub** [comment] 2023-09-10 09:54
@xts-bit react-native-fast-video is a fork of this repo. If there is a feature which needs to be backported, I can try to do it. Let me know

**Comment by xts-bit** [comment] 2023-09-10 10:23
It's great to hear that you're willing to contribute to the React Native Fast Video project by backporting a feature.

I just tried react-native-fast-video but getting this error on Andriod 
```

Could not determine the dependencies of task ':react-native-fast-video:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-fast-video:debugCompileClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer:2.13.2.
     Required by:
         project :react-native-fast-video
   > Could not find com.google.android.exoplayer:extension-okhttp:2.13.2.
     Required by:
         project :react-native-fast-video
```

**Comment by freeboub** [comment] 2023-09-10 10:47
I didn't say I want to contribute to react-native-fast-video :) I said that as react-native-fast-video is a fork of this project, I can backport a patch or feature to react-native-video...
I think it was forked due to lack of maintenance in this repo... but I am here now 😁
The fast-video issue is linked to jcenter. But that is not the place to discuss it.

**Comment by xts-bit** [comment] 2023-09-10 11:59
Yep, I got you, If react-native-video has a terminate video prop it would be great, Multiple videos won't load at the same time or we can sit how many videos to load as you mentioned "stop playback"

**Comment by freeboub** [comment] 2023-09-10 12:07
👍
putting source={undefined} should be ok.

**Comment by xts-bit** [comment] 2023-09-10 14:32
Yep, But it would be great if there was a prop on that :)

Btw. Should I close this issue,

**Comment by freeboub** [comment] 2023-09-10 15:01
Yes I think we can close this issue. Thank you

**Closed as completed** 2023-09-10 15:01 UTC
Labels: demo requested

**Comment by xts-bit** [comment] 2023-09-14 08:49
@freeboub Olivier, Is there any way to turn off the background audio in the video? I mean the video keeps playing but it won't play the audio in the audio? Any prop to do this?

**Comment by xts-bit** [comment] 2023-10-01 12:19
@freeboub Does it support giving me an audio URL and it will play with the video?

**Comment by freeboub** [comment] 2023-10-01 13:56
Mute prop ?

**Comment by xts-bit** [comment] 2023-10-01 14:02
@freeboub No, Like if there is an audio mp3 URL and i want to play that audio in the background with the video like a prop for that

```

<Video source={{ uri: "background.mp4" }}  
  ref={(ref) => {
    this.player = ref
  }}                                    
  onBuffer={this.onBuffer}               
  onError={this.videoError}           
  style={styles.backgroundVideo}
  audio='https://somerandomaudiourlfrominter.mp3'
  />
```

**Comment by xts-bit** [comment] 2023-10-01 15:33
@freeboub It would be great if react-native-video had any prop like that.

**Comment by freeboub** [comment] 2023-10-01 15:54
I think that make sense, but this feature is not available currently, you can open a feature request if you want

**Comment by xts-bit** [comment] 2023-10-01 16:24
@freeboub Yep, i tried to do that https://github.com/react-native-video/react-native-video/issues/3265

**Comment by xts-bit** [comment] 2023-10-02 09:08
@freeboub Do react-native-video have a video caching thing?
