### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by toorandroidmaster** [TheWidlarzGroup/react-native-video#3420] opened 2023-12-13 19:19 UTC
# Bug

Exception java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
  at com.brentvatne.exoplayer.ReactExoplayerView$7$1.run (ReactExoplayerView.java:560)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
  at java.lang.Thread.run (Thread.java:1012)

## Platform
Which player are you experiencing the problem on:
* Android
## Environment info

Library version: 6.0.0-alpha.11
Device:  [Android 12 (SDK 31)]

**Comment by KrzysztofMoch** [comment] 2023-12-15 13:55
Cloud you provide more informations ? Thanks

**Comment by freeboub** [comment] 2023-12-15 16:22
I think I know this issue. It should happen when you  start the app and directly stop it...
The action is null in the reactContext ...

**Comment by toorandroidmaster** [comment] 2023-12-15 19:55
> I think I know this issue. It should happen when you start the app and directly stop it... The action is null in the reactContext ...

Yes @freeboub  you are right ..

**Comment by toorandroidmaster** [comment] 2023-12-18 04:36
> Cloud you provide more informations ? Thank
this is random behaviour error  sometime it throwing this kind of error

**Comment by freeboub** [comment] 2023-12-19 21:53
I just double check, I think the crash has been fixed in last beta version.
Can you double check please ?
I cannot reproduce the crash on my side

**Comment by nicolaosm** [comment] 2024-01-05 08:42
@toorandroidmaster Can you confirm the issue is resolved in v6 beta3 ?

**Closed as not planned** 2024-01-15 11:02 UTC
Labels: Platform: Android, demo requested
