### ISSUE TITLE
Full screen button not showing in Android

### ISSUE THREAD

**Issue by oguzhannkayaa** [TheWidlarzGroup/react-native-video#2637] opened 2022-04-10 12:29 UTC
Versions shown below
 
    "react": "17.0.2",
    "react-native": "^0.67.4",
    "react-native-material-dropdown-v2": "^0.11.1",
    "react-native-reanimated": "^2.3.0",
    "react-native-screens": "^3.13.1",
    "react-native-video": "^5.2.0",

In Android convert fullscreen button not showing

```
  return (
        <Video 
        source={require('./test.mp4')}
        ref={(ref) => {
            this._player = ref
        }}       
        controls={true}
        resizeMode={'stretch'}
        style={styles.backgroundVideo}
       />
  );
}
  var styles = StyleSheet.create({
    backgroundVideo: {
      width:'100%',
      height:'100%'
    },
  });```

**Comment by vargajacint** [comment] 2022-05-08 21:56
I think it's by design behaviour of Exoplayer. [Related topic](https://stackoverflow.com/a/48511657/11423161)
Bdw, you can implement your own logic

**Comment by Nziranziza** [comment] 2022-09-02 09:49
I am having similar issue on android

**Comment by freeboub** [comment] 2022-09-07 20:43
fix ongoing here: https://github.com/react-native-video/react-native-video/pull/2763

**Comment by freeboub** [comment] 2022-09-11 09:59
Merged for 6.0.0-alpha.2

**Closed as completed by freeboub** 2022-09-11 09:59 UTC
Labels: Platform: Android

**Comment by ahmettopal** [comment] 2022-12-02 12:25
I am having similar issue and ı use  "react-native-video": "^6.0.0-alpha.3" version. ı checked #2763 but I did not understand. please help me

**Comment by freeboub** [comment] 2022-12-02 13:03
@ahmettopal please open a dedicated ticket with a full description, how you use the package please

**Comment by ahmettopal** [comment] 2022-12-02 13:25
> please open a dedicated ticket with a full description, how you use the package please

Versions 
first ı use 5.1.2 version then update react-native-video: "^6.0.0-alpha.3"
"react": "18.0.0",
"react-native": "0.69.4",

here you go my code: 

<Video
            ref={(ref) => (videoPlayer.current = ref)}
            source={{ uri: url }}
            paused={true}
            style={styles.backgroundVideo}
            setControls={true}
            controls={true}
            repeat={false}
            fullscreen={true}
            fullscreenAutorotate={true}
            resizeMode={'contain'}
          />

backgroundVideo: {
     height: 200,
    width: 350,
  },

**Comment by freeboub** [comment] 2022-12-02 14:30
Fullscreen button is not displayed if you put Fullscreen=true

**Comment by ahmettopal** [comment] 2022-12-05 11:32
> Fullscreen button is not displayed if you put Fullscreen=true
 
its work thank youu. 👍
