### ISSUE TITLE
[BUG]: Providing startPosition sometimes restarts video from 0 

### ISSUE THREAD

**Issue by mkbhdana** [TheWidlarzGroup/react-native-video#3658] opened 2024-04-05 12:53 UTC
### Version

v6 (Beta)

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

A bug happened!
when startPostion value is provided and opening video multiple times sometimes ignores startPosition and video gets started from beginning and it happens randomly.

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
add source with startPosition providing hardcoded value in ms and then open video multiple times to view the issue as it can happen randomly can be frequent or later. But issue will be visible after few tries.

**Comment by freeboub** [comment] 2024-04-21 20:19
I cannot reproduce the issue with the sample app.
Can you please provide a sample app to reproduce the issue ?

**Comment by mkbhdana** [comment] 2024-04-21 20:22
Will share in the morning.

**Comment by mkbhdana** [comment] 2024-04-23 13:49
@freeboub Currently I am also not facing this issue. Earlier I was using react native media console wrapper where this issue was arising I had done some changes in it and some changes related storage in my code. I guess this was the issue of react native media console.

**Comment by KrzysztofMoch** [comment] 2024-04-25 09:17
So we can close this issue? If not please re-open (or ping me)

**Closed as completed by KrzysztofMoch** 2024-04-25 09:17 UTC
Labels: bug, Platform: Android, demo requested
