### ISSUE TITLE
 ERROR  TypeError: Cannot read property 'resizeMode' of undefined, js engine: hermes

### ISSUE THREAD

**Issue by CHANDRAMOHANnegi** [TheWidlarzGroup/react-native-video#2752] opened 2022-06-30 22:32 UTC
# Bug

 ERROR  TypeError: Cannot read property 'resizeMode' of undefined, js engine: hermes

  posterResizeMode: Image.propTypes.resizeMode,

## Platform
 android  

Which player are you experiencing the problem on:
* Android

## Environment info

react-native :0.69.1
react : 18.2.0

Library version: x.x.x
    "react-native-video": "^5.2.0",

## Steps To Reproduce

Updated  to react-native 0.69.1

 

## Expected behaviour

work fine

**Comment by drplauska** [comment] 2022-07-01 06:35
Also getting this error on iOS.

**Comment by drplauska** [comment] 2022-07-01 06:37
Also getting this on iOS without Hermes.

edit: 
upgrading to `v6.0.0-alpha.1` fixes the problem, just not sure about backwards compatibility.
`yarn add react-native-video@v6.0.0-alpha.1`

**Comment by freeboub** [comment] 2022-07-05 19:15
I confirm this issue is linked to react-native 0.69 and has been fixed on master (V6.0.0-alpha.1) let's close this ticket

**Comment by Zestpond** [comment] 2022-08-12 08:55
But android video has been black screen

**Comment by freeboub** [comment] 2022-08-21 10:14
@Zestpond this is another issue...

**Comment by acuervov** [comment] 2022-08-28 00:29
I still have this issue on iPhone. I get the same error and I'm using this version (V6.0.0-alpha.1)

**Comment by freeboub** [comment] 2022-09-19 07:28
I have find a way to reproduce the issue. I will investigate

**Comment by freeboub** [comment] 2022-09-19 08:50
Ok, i confirm that this issue is fixed in last releases. This was due to imagePropType which is deprecated

**Closed as completed by freeboub** 2022-09-19 08:50 UTC
Labels: critical for release

**Comment by rodrigobertolottizinsp** [comment] 2022-11-10 15:35
Im still facing this issue with react 0.70.5 and  v6.0.0-alpha.1

**Comment by freeboub** [comment] 2022-11-10 16:04
@rodrigobertolottizinsp upgrade react native video please
