### ISSUE TITLE
[BUG]: when open video and out app in background and reopen app => change url crash app.

### ISSUE THREAD

**Issue by megabeehothanhminh** [TheWidlarzGroup/react-native-video#3762] opened 2024-05-12 17:12 UTC
### Version

0.73.1

### What platforms are you having the problem on?

iOS

### Architecture

New architecture with interop layer

### What happened?

  "react-native-video": "^6.0.0-alpha.11"

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
Thread 1: "Cannot remove an observer <NSKeyValueObservance 0x600004c6ea90> for the key path \"currentItem.videoComposition\" from <AVPlayer 0x600000139630>, most likely because the value for the key \"currentItem\" has changed without an appropriate KVO notification being sent. Check the KVO-compliance of the AVPlayer class."

**Comment by freeboub** [comment] 2024-05-12 18:06
Are you able to reproduce with 6.0.0-RC.0 ?

**Comment by megabeehothanhminh** [comment] 2024-05-13 02:32
> Are you able to reproduce with 6.0.0-RC.0 ?

Yes i was update version 6.0.0-RC.0 . But still crash app. 

You can follow steps below.

step 1: open video 
step 2: out app on background
step 3: reopen app and change url. => crash app. 

Mycode: 

<img width="579" alt="Screenshot 2024-05-13 at 09 27 35" src="https://github.com/TheWidlarzGroup/react-native-video/assets/90604279/3885b3f0-e899-460e-b695-05873a20e384">

**Comment by freeboub** [comment] 2024-05-14 08:44
I cannot reproduce the issue with the sample app.
Any clue to help reproduce the issue ?

**Comment by viv3kk** [comment] 2024-05-19 11:05
Getting similar error where app crashes when change network and app goes in background and crashes on foreground.
v5.2.1

**Comment by freeboub** [comment] 2024-05-24 07:53
No update, let's close this issue.
Please update with clear reproduction steps and check if reproduced on 6.1.1

**Closed as completed by freeboub** 2024-05-24 07:53 UTC
Labels: bug
